# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e041d2a01b8fd48c18e1f1b0b2f920"
name = "AI Recommendations"
application_url = "https://eng-adjustment-tax-ranch.trycloudflare.com"

embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zohaib-dev-2.myshopify.com"

[access_scopes]
scopes = "read_orders,read_products,write_products,write_app_proxy"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://eng-adjustment-tax-ranch.trycloudflare.com/auth/callback" ]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks/shop/redact"

[pos]
embedded = false

[app_proxy]
url = "https://eng-adjustment-tax-ranch.trycloudflare.com"
subpath = "recommendations-local"
prefix = "apps"

