# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74e041d2a01b8fd48c18e1f1b0b2f920"
name = "AI Recommendations"
application_url = "https://plastic-keyword-springs-seconds.trycloudflare.com"

embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zohaib-dev-2.myshopify.com"

[access_scopes]
scopes = "read_orders,read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://plastic-keyword-springs-seconds.trycloudflare.com/auth/callback" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[app_proxy]
url = "https://plastic-keyword-springs-seconds.trycloudflare.com"
subpath = "recommendations"
prefix = "apps"

